# ******************************************************************************
#
# Pentaho
#
# Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
#
# Use of this software is governed by the Business Source License included
# in the LICENSE.TXT file.
#
# Change Date: 2030-06-15
# ******************************************************************************
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: "Pentaho Open Source Reports"
description: "Software Bill of Materials (SBOM) for Pentaho products"
